version: '3.4'

services:
  jeager:
    image: jaegertracing/all-in-one:1.53
  elasticsearch:
    image: elasticsearch:8.11.3
  kibana: 
    image: kibana:8.11.3
  prometheus:
    image: prom/prometheus:v2.37.9
    volumes: 
     - ./prometheus.yml:/etc/prometheus/prometheus.yml

