scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: metric.api
    scrape_interval: 2s
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:7187']
    tls_config:
      insecure_skip_verify: true